# Generated by Django 5.1 on 2025-08-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bingousertask",
            name="photo_proof_url",
        ),
        migrations.AddField(
            model_name="bingouserinstance",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("in_progress", "W trakcie"),
                    ("pending_review", "Oczekuje na sprawdzenie"),
                    ("needs_correction", "Wymaga poprawy"),
                    ("completed", "Zakończone"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bingouserinstance",
            name="swap_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bingousertask",
            name="col",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bingousertask",
            name="photo_proof",
            field=models.ImageField(blank=True, null=True, upload_to="bingo_photos/"),
        ),
        migrations.AddField(
            model_name="bingousertask",
            name="row",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
