# Generated by Django 5.1 on 2025-08-15 13:35

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BerealLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Like BeReal",
                "verbose_name_plural": "Lajki BeReal",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BerealNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField()),
                ("deadline", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Powiadomienie BeReal",
                "verbose_name_plural": "Powiadomienia BeReal",
                "ordering": ["-sent_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BerealPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo1",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=False,
                        quality=85,
                        scale=None,
                        size=[1920, 1920],
                        upload_to="bereal",
                    ),
                ),
                (
                    "photo2",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="JPEG",
                        keep_meta=False,
                        quality=85,
                        scale=None,
                        size=[1920, 1920],
                        upload_to="bereal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_late", models.BooleanField(default=False)),
                ("bereal_date", models.DateField()),
            ],
            options={
                "verbose_name": "Post BeReal",
                "verbose_name_plural": "Posty BeReal",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BerealReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Zgłoszenie BeReal",
                "verbose_name_plural": "Zgłoszenia BeReal",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
