# Generated by Django 5.1 on 2025-07-12 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeRealNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_send_time",
                    models.DateTimeField(
                        help_text="Planowany czas wysłania powiadomienia"
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False, help_text="Czy powiadomienie zostało wysłane"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rzeczywisty czas wysłania powiadomienia",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeRealPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_url",
                    models.ImageField(
                        help_text="URL do przechowywanego zdjęcia (tylna kamera)",
                        upload_to="",
                    ),
                ),
                (
                    "photo_url_front",
                    models.ImageField(
                        help_text="URL do przechowywanego zdjęcia (przednia kamera)",
                        upload_to="",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(help_text="Data i godzina wykonania zdjęcia"),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        default=False,
                        help_text="Czy zdjęcie zostało dodane po wyznaczonym czasie",
                    ),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, help_text="Liczba polubień zdjęcia"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Użytkownik, który dodał zdjęcie",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bereal_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeRealPhotoInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.IntegerField(
                        choices=[(1, "like"), (2, "view")],
                        help_text="Typ interakcji: like, view",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data i godzina wykonania interakcji",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        help_text="Zdjęcie, z którym związana jest interakcja",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="bereal.berealphoto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Użytkownik wykonujący akcję",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
