# Generated by Django 5.1 on 2025-08-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bereal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="berealnotification",
            options={
                "ordering": ["-date"],
                "verbose_name": "Powiadomienie BeReal",
                "verbose_name_plural": "Powiadomienia BeReal",
            },
        ),
        migrations.AddField(
            model_name="berealnotification",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="berealnotification",
            name="start",
            field=models.TimeField(default="10:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="berealnotification",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="berealnotification",
            name="deadline",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="berealnotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
