# Generated by Django 5.1 on 2025-07-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bereal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="berealphoto",
            name="view_count",
            field=models.IntegerField(default=0, help_text="Liczba wyświetleń zdjęcia"),
        ),
    ]
