# Generated by Django 5.1 on 2025-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereal", "0002_alter_berealnotification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berealnotification",
            name="deadline",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
