# Generated by Django 5.1 on 2025-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereal", "0003_alter_berealnotification_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berealnotification",
            name="date",
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
