# Generated by Django 4.1 on 2023-05-12 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0002_bus_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="obozstudentow.group",
            ),
        ),
    ]
