# Generated by Django 4.1 on 2023-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0003_alter_announcement_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="map",
            field=models.ImageField(blank=True, upload_to="groups/maps"),
        ),
        migrations.AddField(
            model_name="group",
            name="messenger",
            field=models.URLField(blank=True),
        ),
    ]
