# Generated by Django 4.1 on 2023-05-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0005_user_bus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name_plural": "Buses"},
        ),
        migrations.AddField(
            model_name="scheduleitem",
            name="photo",
            field=models.ImageField(blank=True, upload_to="schedule"),
        ),
    ]
