# Generated by Django 4.1 on 2023-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0006_alter_bus_options_scheduleitem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.ImageField(blank=True, upload_to="links"),
        ),
    ]
