# Generated by Django 4.1 on 2023-06-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0007_alter_link_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointtype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pointtype",
            name="group_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="obozstudentow.grouptype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pointtype",
            name="points_max",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pointtype",
            name="points_min",
            field=models.FloatField(default=0),
        ),
    ]
