# Generated by Django 4.1 on 2023-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0008_pointtype_description_pointtype_group_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="signupsOpen",
            field=models.BooleanField(default=False),
        ),
    ]
