# Generated by Django 4.1 on 2023-06-04 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0009_workshop_signupsopen"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Staff",
        ),
    ]
