# Generated by Django 4.2.2 on 2023-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0010_rename_contact_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
