# Generated by Django 4.2.2 on 2023-06-15 17:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0011_group_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="groups",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="map",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="groups/maps",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="links",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="schedule",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="users",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="workshop",
            ),
        ),
    ]
