# Generated by Django 4.2.2 on 2023-06-15 19:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        (
            "obozstudentow",
            "0012_alter_group_logo_alter_group_map_alter_link_icon_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="group",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
