# Generated by Django 4.2.2 on 2023-06-16 08:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0013_remove_user_username_alter_group_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="links",
            ),
        ),
    ]
