# Generated by Django 4.2.2 on 2023-06-17 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0014_alter_link_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("finish", models.DateTimeField(auto_now_add=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "addedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obozstudentow.group",
                    ),
                ),
            ],
        ),
    ]
