# Generated by Django 4.2.2 on 2023-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0015_dailyquest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="finish",
            field=models.DateTimeField(),
        ),
    ]
