# Generated by Django 4.2.2 on 2023-06-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0016_alter_dailyquest_finish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mealvalidation",
            options={"permissions": [("can_validate_meals", "Can validate meals")]},
        ),
    ]
