# Generated by Django 4.2.2 on 2023-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0017_alter_mealvalidation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterModelOptions(
            name="mealvalidation",
            options={},
        ),
    ]
