# Generated by Django 4.2.2 on 2023-06-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0019_add_groups_and_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"verbose_name": "Ogłoszenie", "verbose_name_plural": "Ogłoszenia"},
        ),
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name_plural": "Busy"},
        ),
        migrations.AlterModelOptions(
            name="dailyquest",
            options={"verbose_name_plural": "Daily questy"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Grupa", "verbose_name_plural": "Grupy"},
        ),
        migrations.AlterModelOptions(
            name="groupmember",
            options={
                "verbose_name": "Członek grupy",
                "verbose_name_plural": "Członkowie grupy",
            },
        ),
        migrations.AlterModelOptions(
            name="grouptype",
            options={
                "verbose_name": "Rodzaj grupy",
                "verbose_name_plural": "Rodzaje grup",
            },
        ),
        migrations.AlterModelOptions(
            name="groupwarden",
            options={
                "verbose_name": "Opiekun grupy",
                "verbose_name_plural": "Opiekunowie grupy",
            },
        ),
        migrations.AlterModelOptions(
            name="lifeguard",
            options={"verbose_name": "Ratownik", "verbose_name_plural": "Ratownicy"},
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={"verbose_name": "Posiłek", "verbose_name_plural": "Posiłki"},
        ),
        migrations.AlterModelOptions(
            name="mealtype",
            options={
                "verbose_name": "Rodzaj posiłku",
                "verbose_name_plural": "Rodzaje posiłków",
            },
        ),
        migrations.AlterModelOptions(
            name="mealvalidation",
            options={
                "verbose_name": "Walidacja posiłku",
                "verbose_name_plural": "Walidacje posiłków",
            },
        ),
        migrations.AlterModelOptions(
            name="point",
            options={"verbose_name": "Punkty", "verbose_name_plural": "Punkty"},
        ),
        migrations.AlterModelOptions(
            name="pointtype",
            options={
                "verbose_name": "Rodzaj punktu",
                "verbose_name_plural": "Rodzaje punktów",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduleitem",
            options={
                "verbose_name": "Harmonogram",
                "verbose_name_plural": "Harmonogram",
            },
        ),
        migrations.AlterModelOptions(
            name="soberduty",
            options={
                "verbose_name": "Dyżur trzeźwości",
                "verbose_name_plural": "Dyżury trzeźwości",
            },
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Sztab", "verbose_name_plural": "Sztab"},
        ),
        migrations.AlterModelOptions(
            name="workshop",
            options={"verbose_name": "Warsztat", "verbose_name_plural": "Warsztaty"},
        ),
        migrations.AlterModelOptions(
            name="workshopleader",
            options={
                "verbose_name": "Prowadzący warsztaty",
                "verbose_name_plural": "Prowadzący warsztaty",
            },
        ),
        migrations.AlterModelOptions(
            name="workshopsignup",
            options={
                "verbose_name": "Zapis na warsztaty",
                "verbose_name_plural": "Zapisy na warsztaty",
            },
        ),
        migrations.RemoveField(
            model_name="dailyquest",
            name="content",
        ),
        migrations.AddField(
            model_name="dailyquest",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyquest",
            name="title",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
