# Generated by Django 4.2.2 on 2023-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0020_alter_announcement_options_alter_bus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquest",
            name="points",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
