# Generated by Django 4.2.2 on 2023-06-19 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0021_dailyquest_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealtype",
            name="end",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mealtype",
            name="start",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
