# Generated by Django 4.2.2 on 2023-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0022_mealtype_end_mealtype_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images")),
            ],
            options={
                "verbose_name_plural": "Obrazki",
            },
        ),
    ]
