# Generated by Django 4.2.2 on 2023-06-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0024_add_permissions"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
