# Generated by Django 4.2.2 on 2023-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0025_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="signupsOpenTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
