# Generated by Django 4.2.2 on 2023-06-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0026_workshop_signupsopentime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="icons")),
            ],
            options={
                "verbose_name": "Ikonka",
                "verbose_name_plural": "Ikonki",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Obrazek", "verbose_name_plural": "Obrazki"},
        ),
    ]
