# Generated by Django 4.2.2 on 2023-06-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0027_icons_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="obozstudentow.icons",
            ),
        ),
    ]
