# Generated by Django 4.2.2 on 2023-06-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0028_alter_link_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="point",
            name="validatedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validatedBy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="point",
            name="validationDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
