# Generated by Django 4.2.2 on 2023-07-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0030_add_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
