# Generated by Django 4.2.2 on 2023-07-05 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0031_point_rejected"),
    ]

    operations = [
        migrations.CreateModel(
            name="NightGameSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_band", models.CharField(max_length=10)),
                ("user_first_name", models.CharField(max_length=150)),
                ("user_last_name", models.CharField(max_length=150)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("failed", models.BooleanField(default=False)),
                (
                    "addedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addedBy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="obozstudentow.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zapis na nocną",
                "verbose_name_plural": "Zapisy na nocne",
            },
        ),
    ]
