# Generated by Django 4.2.2 on 2023-07-05 19:33

from django.db import migrations, models

def create_groups_limit_setting(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")
    Setting.objects.create(name="group_limit", value="0")
    Setting.objects.create(name="group_user_min", value="3")
    Setting.objects.create(name="group_user_max", value="6")

class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0032_nightgamesignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Ustawienie",
                "verbose_name_plural": "Ustawienia",
            },
        ),
        migrations.RunPython(create_groups_limit_setting)
    ]
