# Generated by Django 4.2.2 on 2023-07-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0033_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="nightgamesignup",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
