# Generated by Django 4.2.2 on 2023-07-08 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0034_nightgamesignup_error"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nightgamesignup",
            options={
                "verbose_name": "Zapis na grę nocną",
                "verbose_name_plural": "Zapisy na grę nocną",
            },
        ),
        migrations.AddField(
            model_name="mealvalidation",
            name="validatedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_validations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
