# Generated by Django 4.2.2 on 2023-07-08 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0036_userfcmtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfcmtoken",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
