# Generated by Django 4.2.2 on 2023-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0037_userfcmtoken_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="hide_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
