# Generated by Django 4.2.2 on 2023-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0038_announcement_hide_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="itemsToTake",
            field=models.TextField(blank=True),
        ),
    ]
