# Generated by Django 4.2.2 on 2023-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0039_workshop_itemstotake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitem",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
