# Generated by Django 4.2.2 on 2023-08-17 16:43

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0040_alter_scheduleitem_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bandId",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="diet",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="houseNumber",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                null=True,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="users",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
