# Generated by Django 4.2.2 on 2023-08-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0041_alter_user_bandid_alter_user_diet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="itemsToTake",
            field=models.TextField(blank=True, null=True),
        ),
    ]
