# Generated by Django 4.2.2 on 2023-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0042_alter_workshop_itemstotake"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
