# Generated by Django 4.2.2 on 2023-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0044_new_settngs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
