# Generated by Django 4.2.2 on 2023-08-19 20:23

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0046_user_freenow_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="groups"),
        ),
        migrations.AlterField(
            model_name="group",
            name="map",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=False,
                null=True,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="groups/maps",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="messenger",
            field=models.URLField(blank=True, null=True),
        ),
    ]
