# Generated by Django 4.2.2 on 2023-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0047_alter_group_description_alter_group_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
