# Generated by Django 4.2.2 on 2023-08-20 16:24

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0049_partners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partners",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partners",
            name="logo",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=False,
                quality=85,
                scale=None,
                size=[400, 400],
                upload_to="partners",
            ),
        ),
    ]
