# Generated by Django 4.2.2 on 2023-08-21 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0050_alter_partners_link_alter_partners_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kadra",
            fields=[],
            options={
                "verbose_name": "Kadrowicz",
                "verbose_name_plural": "Kadra",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("obozstudentow.user",),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[],
            options={
                "verbose_name": "Uczestnik",
                "verbose_name_plural": "Uczestnicy",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("obozstudentow.user",),
        ),
    ]
