# Generated by Django 4.2.2 on 2023-08-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0051_kadra_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sztab",
            fields=[],
            options={
                "verbose_name": "Sztab",
                "verbose_name_plural": "Sztab",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("obozstudentow.user",),
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={
                "verbose_name": "Kontakt do sztabu",
                "verbose_name_plural": "Kontakty do sztabu",
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, default=0),
            preserve_default=False,
        ),
    ]
