# Generated by Django 4.2.2 on 2023-08-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0052_sztab_alter_staff_options_staff_sort_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Kontakt do sztabu",
                "verbose_name_plural": "Kontakty do sztabu",
            },
        ),
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
