# Generated by Django 4.2.2 on 2023-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0053_alter_staff_options_alter_staff_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="backgroud",
            field=models.ImageField(
                blank=True, null=True, upload_to="groups/backgrounds"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="images"),
        ),
    ]
