# Generated by Django 4.2.2 on 2023-08-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0054_group_backgroud_alter_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="backgroud",
            new_name="background",
        ),
    ]
