# Generated by Django 4.2.2 on 2023-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0055_rename_backgroud_group_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("key_collected", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Domek",
                "verbose_name_plural": "Domki",
            },
        ),
    ]
