# Generated by Django 4.2.2 on 2023-08-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0056_house"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="houseNumber",
        ),
        migrations.AddField(
            model_name="user",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="obozstudentow.house",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="key_collected",
            field=models.BooleanField(default=False, verbose_name="Klucz odebrany"),
        ),
    ]
