# Generated by Django 4.2.2 on 2023-07-05 19:33

from django.db import migrations, models


def create_settings(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")

    Setting.objects.create(
        name="night_game_signup_active",
        value="false",
        description="Zapisy na grę nocną aktywne",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0057_remove_user_housenumber_user_house_and_more"),
    ]

    operations = [migrations.RunPython(create_settings)]
