# Generated by Django 4.2.2 on 2023-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0058_new_settngs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bandId",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
