# Generated by Django 4.2.2 on 2023-08-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0060_housecollocationforimport_alter_user_bandid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="housecollocationforimport",
            old_name="name",
            new_name="house",
        ),
    ]
