# Generated by Django 4.2.2 on 2023-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0061_rename_name_housecollocationforimport_house"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Grupa",
                "verbose_name_plural": "Grupy",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
