# Generated by Django 4.2.2 on 2023-07-05 19:33

from django.db import migrations, models


def create_settings(apps, schema_editor):
    Group = apps.get_model("obozstudentow", "Group")
    for group in Group.objects.all():
        group.sort_order = group.id
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0062_alter_group_options_group_sort_order"),
    ]

    operations = [migrations.RunPython(create_settings)]
