# Generated by Django 4.2.2 on 2023-08-26 14:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0063_add_order_to_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="faq",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=False,
                null=True,
                quality=85,
                scale=None,
                size=[1920, 1080],
                upload_to="users",
            ),
        ),
    ]
