# Generated by Django 4.2.2 on 2023-08-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0065_add_order_to_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Link w profilu",
                "verbose_name_plural": "Linki w profilu",
            },
        ),
        migrations.AddField(
            model_name="link",
            name="sort_order",
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HomeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="home_links"),
                ),
                ("visible", models.BooleanField(default=False)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="obozstudentow.icons",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link w home",
                "verbose_name_plural": "Linki w home",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
