# Generated by Django 4.2.2 on 2023-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0067_add_order_to_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homelink",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
