# Generated by Django 4.2.2 on 2023-08-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0068_alter_homelink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
