# Generated by Django 4.2.2 on 2023-08-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0069_image_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="hide_map",
            field=models.BooleanField(default=False),
        ),
    ]
