# Generated by Django 4.2.2 on 2023-08-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0071_add_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={},
        ),
    ]
