# Generated by Django 4.2.2 on 2023-08-28 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0072_alter_faq_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
