# Generated by Django 4.2.2 on 2023-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0073_alter_faq_options_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyquest",
            name="points",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
