# Generated by Django 4.2.2 on 2023-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0074_alter_dailyquest_finish_alter_dailyquest_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquest",
            name="points",
            field=models.FloatField(null=True),
        ),
    ]
