# Generated by Django 4.2.2 on 2023-09-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0076_alter_dailyquest_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="places",
            field=models.IntegerField(default=0, verbose_name="Liczba miejsc"),
        ),
    ]
