# Generated by Django 4.2.2 on 2023-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0077_house_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyquest",
            name="start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
