# Generated by Django 4.2.2 on 2023-09-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0078_dailyquest_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyquest",
            name="addedBy",
        ),
    ]
