# Generated by Django 4.2.2 on 2023-07-05 19:33

from django.db import migrations, models

def create_settings(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")

    Setting.objects.create(name="allow_multiple_workshops_same_day", value="true", description="Czy użytownik może zapisać się na więcej niż jedne warsztaty w tym samym dniu?")

class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0079_remove_dailyquest_addedby"),
    ]

    operations = [
        migrations.RunPython(create_settings)
    ]
