# Generated by Django 5.0 on 2024-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow', '0084_houseview_house_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Pokój/domek', 'verbose_name_plural': 'Pokoje/domki'},
        ),
        migrations.AddField(
            model_name='house',
            name='signout_open',
            field=models.BooleanField(default=True, verbose_name='Czy można się wypisać z domku/pokoju'),
        ),
        migrations.AddField(
            model_name='house',
            name='signup_open',
            field=models.BooleanField(default=True, verbose_name='Czy można się zapisać do domku/pokoju'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Numer domku/pokoju'),
        ),
    ]
