# Generated by Django 5.0.3 on 2024-04-28 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0088_user_verification_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="freenow_code",
        ),
    ]
