# Generated by Django 5.0.3 on 2024-04-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow', '0093_new_settings_signup_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opaski',
            fields=[
            ],
            options={
                'verbose_name': 'Opaski',
                'verbose_name_plural': 'Opaski',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('obozstudentow.user',),
        ),
    ]
