# Generated by Django 5.0.6 on 2024-08-18 11:30

from django.db import migrations, models


def enable_notifications(apps, schema_editor):
    User = apps.get_model("obozstudentow", "User")
    User.objects.filter(userfcmtoken__isnull=False).update(notifications=True)


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0101_create_more_sztab_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            enable_notifications, reverse_code=migrations.RunPython.noop
        ),
    ]
