# Generated by Django 5.0.6 on 2024-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow', '0104_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bus_presence',
            field=models.BooleanField(default=False),
        ),
    ]
