# Generated by Django 5.0.6 on 2024-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0108_create_more_sztab_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bus_presence_return",
            field=models.BooleanField(default=False),
        ),
    ]
