# Generated by Django 5.0.6 on 2024-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0109_user_bus_presence_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bus_info",
            field=models.CharField(
                choices=[
                    ("both", "Obie strony lub żadna"),
                    ("to", "Tylko tam"),
                    ("return", "Tylko z powrotem"),
                ],
                default="both",
                max_length=6,
            ),
        ),
    ]
