# Generated by Django 4.2.2 on 2023-07-05 19:33

from django.db import migrations, models


def create_settings(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")

    Setting.objects.create(
        name="bus_presence",
        value="to",
        description='Typ sprawdzania obecności w busach ("to", "return", "" - nieaktywne)',
    )


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0110_user_bus_info"),
    ]

    operations = [migrations.RunPython(create_settings)]
