# Generated by Django 5.0.6 on 2024-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0113_new_settings_tinder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="location",
            field=models.URLField(blank=True, null=True),
        ),
    ]
