# Generated by Django 5.0.6 on 2024-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow', '0115_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinderprofile',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
