# Generated by Django 5.1 on 2025-08-14 17:16

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow', '0120_add_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerealNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Powiadomienie BeReal',
                'verbose_name_plural': 'Powiadomienia BeReal',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BeerealPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=False, quality=85, scale=None, size=[1080, 1080], upload_to='bereal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False)),
                ('bereal_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bereal_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post BeReal',
                'verbose_name_plural': 'Posty BeReal',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'bereal_date')},
            },
        ),
        migrations.CreateModel(
            name='BeerealLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='obozstudentow.beerealpost')),
            ],
            options={
                'verbose_name': 'Like BeReal',
                'verbose_name_plural': 'Lajki BeReal',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='BeerealReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='obozstudentow.beerealpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bereal_reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bereal_reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zgłoszenie BeReal',
                'verbose_name_plural': 'Zgłoszenia BeReal',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'post')},
            },
        ),
    ]
