# Generated by Django 5.1 on 2025-08-15 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0121_add_bereal_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tinderprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="TinderAction",
        ),
        migrations.DeleteModel(
            name="TinderProfile",
        ),
    ]
