# Generated by Django 5.1 on 2025-08-14 18:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0122_add_bereal_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beerealpost",
            name="photo",
        ),
        migrations.AddField(
            model_name="beerealpost",
            name="photo1",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=0,
                force_format="jpg",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1920],
                upload_to="bereal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beerealpost",
            name="photo2",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=0,
                force_format="jpg",
                keep_meta=False,
                quality=85,
                scale=None,
                size=[1920, 1920],
                upload_to="bereal",
            ),
            preserve_default=False,
        ),
    ]
