# Generated by GitHub Copilot on 2025-08-17
from django.db import migrations


def add_bereal_time_settings(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")
    defaults = {
        "bereal_time_start": (
            "10",
            "Godzina (0-23) od której może rozpocząć się okno BeReal",
        ),
        "bereal_time_end": (
            "22",
            "Godzina (0-23) do której może rozpocząć się okno BeReal",
        ),
        "bereal_deadline_minutes": (
            "3",
            "Ile minut ma użytkownik na odpowiedź od startu okna",
        ),
    }
    for name, (value, description) in defaults.items():
        Setting.objects.get_or_create(
            name=name,
            defaults={"value": value, "description": description},
        )


def remove_bereal_time_settings(apps, schema_editor):
    Setting = apps.get_model("obozstudentow", "Setting")
    Setting.objects.filter(
        name__in=[
            "bereal_time_start",
            "bereal_time_end",
            "bereal_deadline_minutes",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "obozstudentow",
            "0122_remove_tinderprofile_user_delete_tinderaction_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(add_bereal_time_settings, remove_bereal_time_settings),
    ]
