# Generated by Django 5.1 on 2025-08-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0123_remove_beerealpost_photo_beerealpost_photo1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BeerealReport",
            new_name="BerealReport",
        ),
    ]
