# Generated by Django 5.1 on 2025-08-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0123_add_bereal_time_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="notifications_sent",
            field=models.BooleanField(default=False),
        ),
    ]
