# Generated by Django 5.1 on 2025-08-14 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("obozstudentow", "0124_rename_beerealreport_berealreport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BeerealLike",
            new_name="BerealLike",
        ),
    ]
