# Generated by Django 5.1 on 2025-08-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0125_rename_beereallike_bereallike"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BeerealPost",
            new_name="BerealPost",
        ),
    ]
