# Generated by Django 5.1 on 2025-08-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("obozstudentow", "0126_rename_beerealpost_berealpost"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BeerealNotification",
            new_name="BerealNotification",
        ),
    ]
