# Generated by Django 5.0.6 on 2024-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obozstudentow_async', '0003_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
