name: Black Formatter

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch and update main
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Create Black branch
        run: |
          BRANCH=black-fix/$(date +"%Y%m%d%H%M%S")
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b $BRANCH

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black .

      - name: Commit changes if needed
        id: commit-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Apply Black code formatting"
            git push --set-upstream origin $BRANCH
            echo "changes_committed=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "changes_committed=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request if needed
        if: ${{ env.changes_committed == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.BRANCH }}
          title: "Apply Black code formatting"
          body: "Automated Black formatting changes."
          base: main