name: Black Formatter

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch and update main
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Create Black branch
        id: create-branch
        run: |
          BRANCH=black-fix/$(date +"%Y%m%d%H%M%S")
          git checkout -b $BRANCH
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Install Black
        run: pip install black

      - name: Run Black
        run: black .

      - name: Create Pull Request if needed
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ steps.create-branch.outputs.branch }}
          title: "Apply Black code formatting"
          body: "Automated Black formatting changes."
          base: main
          commit-message: "Apply Black code formatting"